"""empty message

Revision ID: 296fdc1088be
Revises: 5ee8213a0a15
Create Date: 2022-11-14 18:00:13.311024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296fdc1088be'
down_revision = '5ee8213a0a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('owner', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'owner')
    # ### end Alembic commands ###
