"""empty message

Revision ID: 374f9d8f9066
Revises: d9f89dc1e893
Create Date: 2022-11-14 12:26:36.874397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '374f9d8f9066'
down_revision = 'd9f89dc1e893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('task', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
