"""empty message

Revision ID: d9f89dc1e893
Revises: b1bb0c586d59
Create Date: 2022-09-22 14:27:16.469936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f89dc1e893'
down_revision = 'b1bb0c586d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
